### ISSUE TITLE
reformat as package

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/testkraken#57]
@djarecka - i would like to reformat this project as a python package. at the moment, it is not pip-installable. it won't take much time, but the change would introduce merge conflicts with existing PRs. can we merge the existing PRs once they are ready, and then i can make this change?

**Comment by djarecka** [comment]
great, feel free. 

I don't want to merge the one with afni before I find why the parallel plot doesn't work there. I can try to do it tomorrow, but can't promise, since I'm still working on d3...
But the PRs mostly introduced new files, so I should be able update it to the new structure without too much work, so don't worry!

In my current branch I'm mostly changing dashboard, so also shouldn't be a problem.

**Comment by kaczmarj** [comment]
Resolved by #58
